[package]
name = "traffic_light_control"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.21", features = ["auto-initialize"] }
# Remember to set python -> /python/.venv/bin/python, we are using python 3.9 now.
rusqlite = { version = "0.38", features = ["bundled"] }
once_cell = "1.17"
eframe = "0.31"
egui = "0.31"
rand = "0.9"
rfd = "0.14"
image = "0.25"
