-- Generated by Copilot & ChatGPT 5.2
-- Week test data aligned with class schedule and realistic flow estimates.
--
-- Pedestrian estimate (per intersection): peak ~250 people/min (≈4–5 people/s)
-- Vehicle estimate: baseline ~5–10 vehicles/min
--
-- We generate minute-level records for the last 7 days:
--  - pre-class peak window: [-20, -5) minutes before class start (15 minutes)
--  - post-class peak window: [0, +15) minutes after class end (15 minutes)
--  - additionally, add low baseline during class time at 10-minute granularity
--
-- Tables: vehicle_fuzzy_results(timestamp, obj_count), pedestrian_fuzzy_results(timestamp, obj_count)
-- timestamp is unix seconds.

BEGIN;

PRAGMA foreign_keys = ON;

-- Optional: clear existing rows to make reruns deterministic
DELETE FROM vehicle_fuzzy_results;
DELETE FROM pedestrian_fuzzy_results;

-- 1) Pedestrian pre-class peak: 15 minutes, ~250/min with small variation
WITH RECURSIVE
  days(d) AS (SELECT 1 UNION ALL SELECT d + 1 FROM days WHERE d < 7),
  periods(p, start_h, start_m, end_h, end_m) AS (
    VALUES
      (1,  8, 30, 10,  5),
      (2, 10, 25, 12,  0),
      (3, 13, 50, 15, 25),
      (4, 15, 45, 17, 20),
      (5, 18, 20, 20, 40)
  ),
  pre_min(m) AS (SELECT 0 UNION ALL SELECT m + 1 FROM pre_min WHERE m < 14)
INSERT INTO pedestrian_fuzzy_results(timestamp, obj_count)
SELECT
  CAST(strftime('%s', 'now',
    '-' || days.d || ' day',
    'start of day',
    '+' || periods.start_h || ' hours',
    '+' || periods.start_m || ' minutes',
    '-20 minutes',
    '+' || pre_min.m || ' minutes'
  ) AS INTEGER) AS ts,
  240 + ((days.d * 17 + periods.p * 11 + pre_min.m * 7) % 21) AS obj_count
FROM days
CROSS JOIN periods
CROSS JOIN pre_min;

-- 2) Pedestrian post-class peak: 15 minutes after end, ~250/min with small variation
WITH RECURSIVE
  days(d) AS (SELECT 1 UNION ALL SELECT d + 1 FROM days WHERE d < 7),
  periods(p, start_h, start_m, end_h, end_m) AS (
    VALUES
      (1,  8, 30, 10,  5),
      (2, 10, 25, 12,  0),
      (3, 13, 50, 15, 25),
      (4, 15, 45, 17, 20),
      (5, 18, 20, 20, 40)
  ),
  post_min(m) AS (SELECT 0 UNION ALL SELECT m + 1 FROM post_min WHERE m < 14)
INSERT INTO pedestrian_fuzzy_results(timestamp, obj_count)
SELECT
  CAST(strftime('%s', 'now',
    '-' || days.d || ' day',
    'start of day',
    '+' || periods.end_h || ' hours',
    '+' || periods.end_m || ' minutes',
    '+' || post_min.m || ' minutes'
  ) AS INTEGER) AS ts,
  235 + ((days.d * 19 + periods.p * 13 + post_min.m * 5) % 31) AS obj_count
FROM days
CROSS JOIN periods
CROSS JOIN post_min;

-- 3) Pedestrian baseline during class time: every 10 minutes, low steady flow (30..60)
WITH RECURSIVE
  days(d) AS (SELECT 1 UNION ALL SELECT d + 1 FROM days WHERE d < 7),
  periods(p, start_h, start_m, end_h, end_m) AS (
    VALUES
      (1,  8, 30, 10,  5),
      (2, 10, 25, 12,  0),
      (3, 13, 50, 15, 25),
      (4, 15, 45, 17, 20),
      (5, 18, 20, 20, 40)
  ),
  class_10min(m) AS (SELECT 0 UNION ALL SELECT m + 10 FROM class_10min WHERE m < 90)
INSERT INTO pedestrian_fuzzy_results(timestamp, obj_count)
SELECT
  CAST(strftime('%s', 'now',
    '-' || days.d || ' day',
    'start of day',
    '+' || periods.start_h || ' hours',
    '+' || periods.start_m || ' minutes',
    '+' || class_10min.m || ' minutes'
  ) AS INTEGER) AS ts,
  30 + ((days.d * 23 + periods.p * 7 + class_10min.m) % 31) AS obj_count
FROM days
CROSS JOIN periods
CROSS JOIN class_10min;

-- 4) Vehicle during peaks: 15 minutes each window, 8..14 vehicles/min
WITH RECURSIVE
  days(d) AS (SELECT 1 UNION ALL SELECT d + 1 FROM days WHERE d < 7),
  periods(p, start_h, start_m, end_h, end_m) AS (
    VALUES
      (1,  8, 30, 10,  5),
      (2, 10, 25, 12,  0),
      (3, 13, 50, 15, 25),
      (4, 15, 45, 17, 20),
      (5, 18, 20, 20, 40)
  ),
  pre_min(m) AS (SELECT 0 UNION ALL SELECT m + 1 FROM pre_min WHERE m < 14)
INSERT INTO vehicle_fuzzy_results(timestamp, obj_count)
SELECT
  CAST(strftime('%s', 'now',
    '-' || days.d || ' day',
    'start of day',
    '+' || periods.start_h || ' hours',
    '+' || periods.start_m || ' minutes',
    '-20 minutes',
    '+' || pre_min.m || ' minutes'
  ) AS INTEGER) AS ts,
  8 + ((days.d * 7 + periods.p * 5 + pre_min.m * 3) % 7) AS obj_count
FROM days
CROSS JOIN periods
CROSS JOIN pre_min;

WITH RECURSIVE
  days(d) AS (SELECT 1 UNION ALL SELECT d + 1 FROM days WHERE d < 7),
  periods(p, start_h, start_m, end_h, end_m) AS (
    VALUES
      (1,  8, 30, 10,  5),
      (2, 10, 25, 12,  0),
      (3, 13, 50, 15, 25),
      (4, 15, 45, 17, 20),
      (5, 18, 20, 20, 40)
  ),
  post_min(m) AS (SELECT 0 UNION ALL SELECT m + 1 FROM post_min WHERE m < 14)
INSERT INTO vehicle_fuzzy_results(timestamp, obj_count)
SELECT
  CAST(strftime('%s', 'now',
    '-' || days.d || ' day',
    'start of day',
    '+' || periods.end_h || ' hours',
    '+' || periods.end_m || ' minutes',
    '+' || post_min.m || ' minutes'
  ) AS INTEGER) AS ts,
  8 + ((days.d * 11 + periods.p * 3 + post_min.m * 2) % 7) AS obj_count
FROM days
CROSS JOIN periods
CROSS JOIN post_min;

-- 5) Vehicle baseline during class time: every 10 minutes, 5..10 vehicles
WITH RECURSIVE
  days(d) AS (SELECT 1 UNION ALL SELECT d + 1 FROM days WHERE d < 7),
  periods(p, start_h, start_m, end_h, end_m) AS (
    VALUES
      (1,  8, 30, 10,  5),
      (2, 10, 25, 12,  0),
      (3, 13, 50, 15, 25),
      (4, 15, 45, 17, 20),
      (5, 18, 20, 20, 40)
  ),
  class_10min(m) AS (SELECT 0 UNION ALL SELECT m + 10 FROM class_10min WHERE m < 90)
INSERT INTO vehicle_fuzzy_results(timestamp, obj_count)
SELECT
  CAST(strftime('%s', 'now',
    '-' || days.d || ' day',
    'start of day',
    '+' || periods.start_h || ' hours',
    '+' || periods.start_m || ' minutes',
    '+' || class_10min.m || ' minutes'
  ) AS INTEGER) AS ts,
  5 + ((days.d * 13 + periods.p * 9 + class_10min.m) % 6) AS obj_count
FROM days
CROSS JOIN periods
CROSS JOIN class_10min;

COMMIT;
